services:
  frontend:
    build: ./packages/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3000
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./packages/backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
