version: "3.8"
services:
  frontend:
    build: ./packages/frontend
    container_name: frontend
    ports:
      - '5173:5173'
  backend:
    build: ./packages/backend
    container_name: backend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true